# CircleCI config
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/challenge-bypass-extension
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --init
      - run:
          name: Fetching Sources
          command: make install
      - run:
          name: Linting
          command: make lint
      - run:
          name: Building
          command: make clean sjcl build
      - run:
          name: Testing
          command: make test-all
